# Generated by Django 2.0.7 on 2018-07-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_auto_20180703_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicChr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='arcane_arts',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='divine_ct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='divine_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='divinity_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='elem_features',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='expert_skills',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='fly_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='invocations',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='jack_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='jack_skills',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='ki_opts',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='maneuver_arts',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='master_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='metamagic',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='oath',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='rage_ct',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='rage_desc',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='rage_dmg',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='sig_spells',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='sneak_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='sneak_dmg',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='sorcery_pts',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='speed',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='spell_master',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='spell_slot_ct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='spellbook_ct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='style',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='superiority_dice',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='swim_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basechrclass',
            name='tradition',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='race',
            name='advantages',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='race',
            name='attacks',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='race',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='race',
            name='disadvantages',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='race',
            name='features',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='race',
            name='fly_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='proficiency',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='race',
            name='resistances',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='race',
            name='subrace',
            field=models.CharField(default='', max_length=100),
        ),
    ]
