# Generated by Django 2.0.7 on 2018-07-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_auto_20180703_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicchr',
            name='cantrips',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='magicchr',
            name='eight',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='magicchr',
            name='five',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='magicchr',
            name='four',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='magicchr',
            name='magic_attack',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='magicchr',
            name='magic_ct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magicchr',
            name='magic_dc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magicchr',
            name='magic_throw',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='magicchr',
            name='nine',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='magicchr',
            name='one',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='magicchr',
            name='seven',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='magicchr',
            name='six',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='magicchr',
            name='three',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='magicchr',
            name='two',
            field=models.CharField(default='', max_length=200),
        ),
    ]
