from django.db import models


class Character(models.Model):
    chr_name = models.CharField(max_length=50, default="No Name")
    level = models.IntegerField(default=1)
    player_name = models.CharField(max_length=50, default="No Player")
    race = models.CharField(max_length=10, default="Human")
    clas = models.CharField(max_length=9, default="Barbarian")
    gender = models.CharField(max_length=10, default="straight")
    sex = models.CharField(max_length=10, default="male")
    strength = models.IntegerField(default=1)
    dexterity = models.IntegerField(default=1)
    charisma = models.IntegerField(default=1)
    constitution = models.IntegerField(default=1)
    intelligence = models.IntegerField(default=1)
    wisdom = models.IntegerField(default=1)
    traits = models.CharField(max_length=200, default="No traits")
    ideals = models.CharField(max_length=200, default="No ideals")
    bond = models.CharField(max_length=200, default="No bonds")
    flaw = models.CharField(max_length=200, default="No flaws (perfection)")
    alignment = models.CharField(max_length=2, default="TN")

    def __str__(self):
        return self.chr_name + " as a string"


class Race(models.Model):
    race = models.CharField(max_length=10, default="")
    str_add = models.IntegerField(default=0)
    dex_add = models.IntegerField(default=0)
    wis_add = models.IntegerField(default=0)
    int_add = models.IntegerField(default=0)
    cha_add = models.IntegerField(default=0)
    con_add = models.IntegerField(default=0)
    age = models.IntegerField(default=18)
    weight = models.IntegerField(default=100)
    height = models.IntegerField(default=65)
    size = models.CharField(max_length=10, default="")
    speed = models.IntegerField(default=30)
    languages = models.CharField(max_length=300, default="")
    resistances = models.CharField(max_length=300, default="")
    attacks = models.CharField(max_length=300, default="")
    color = models.CharField(max_length=50, default="")
    proficiency = models.CharField(max_length=200, default="")
    subrace = models.CharField(max_length=100, default="")
    disadvantages = models.CharField(max_length=300, default="")
    advantages = models.CharField(max_length=300, default="")
    fly_speed = models.IntegerField(default=0)
    features = models.CharField(max_length=300, default="")


class BaseChrClass(models.Model):
    clas = models.CharField(max_length=9, default="")
    str_add = models.IntegerField(default=0)
    dex_add = models.IntegerField(default=0)
    wis_add = models.IntegerField(default=0)
    int_add = models.IntegerField(default=0)
    cha_add = models.IntegerField(default=0)
    con_add = models.IntegerField(default=0)
    equip = models.CharField(max_length=500, default="")
    hp = models.IntegerField(default=1)
    skills = models.CharField(max_length=500, default="")
    archetype = models.CharField(max_length=20, default="")
    proficiency = models.CharField(max_length=200, default="")
    prof_bonus = models.IntegerField(default=1)
    armor_name = models.CharField(max_length=10, default="")
    armor_ac = models.IntegerField(default=8)
    resistances = models.CharField(max_length=300, default="")
    weapons = models.CharField(max_length=300, default="")
    features = models.CharField(max_length=300, default="")
    saving_throw = models.CharField(max_length=50, default="")
    hit_dice = models.CharField(max_length=6, default="")
    attacks = models.CharField(max_length=300, default="")
    path = models.CharField(max_length=100, default="")
    swim_speed = models.IntegerField(default=0)
    rage_desc = models.CharField(max_length=150, default="")
    rage_ct = models.IntegerField(default=-1)
    rage_dmg = models.IntegerField(default=-1)
    jack_bonus = models.IntegerField(default=0)
    jack_skills = models.CharField(max_length=200, default="")
    divine_ct = models.IntegerField(default=0)
    divine_desc = models.CharField(max_length=200, default="")
    arcane_arts = models.CharField(max_length=200, default="")
    maneuver_arts = models.CharField(max_length=200, default="")
    superiority_dice = models.CharField(max_length=5, default="")
    ki_opts = models.CharField(max_length=200, default="")
    elem_features = models.CharField(max_length=200, default="")
    oath = models.CharField(max_length=50, default="")
    divinity_desc = models.CharField(max_length=200, default="")
    style = models.CharField(max_length=200, default="")
    master_desc = models.CharField(max_length=200, default="")
    sneak_desc = models.CharField(max_length=200, default="")
    sneak_dmg = models.CharField(max_length=200, default="")
    expert_skills = models.CharField(max_length=200, default="")
    speed = models.IntegerField(default=30)
    metamagic = models.CharField(max_length=200, default="")
    color = models.CharField(max_length=50, default="")
    fly_speed = models.IntegerField(default=0)
    sorcery_pts = models.CharField(max_length=200, default="")
    invocations = models.CharField(max_length=200, default="")
    spell_slot_ct = models.IntegerField(default=0)
    spellbook_ct = models.IntegerField(default=0)
    spell_master = models.CharField(max_length=200, default="")
    sig_spells = models.CharField(max_length=200, default="")
    tradition = models.CharField(max_length=200, default="")


class MagicChr(models.Model):
    magic_throw = models.CharField(max_length=10, default="")
    magic_dc = models.IntegerField(default=0)
    magic_attack = models.CharField(max_length=200, default="")
    magic_ct = models.IntegerField(default=0)
    cantrips = models.CharField(max_length=200, default="")
    one = models.CharField(max_length=200, default="")
    two = models.CharField(max_length=200, default="")
    three = models.CharField(max_length=200, default="")
    four = models.CharField(max_length=200, default="")
    five = models.CharField(max_length=200, default="")
    six = models.CharField(max_length=200, default="")
    seven = models.CharField(max_length=200, default="")
    eight = models.CharField(max_length=200, default="")
    nine = models.CharField(max_length=200, default="")







